# Generated by Django 5.0.2 on 2024-03-31 00:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agee_code",
                    models.CharField(
                        help_text="AGEE code of this locality.",
                        max_length=2,
                        verbose_name="AGEE code",
                    ),
                ),
                (
                    "agee_name",
                    models.CharField(
                        help_text="AGEE name of this locality.",
                        max_length=30,
                        verbose_name="AGEE name",
                    ),
                ),
                (
                    "agem_code",
                    models.CharField(
                        help_text="AGEM code of this locality.",
                        max_length=3,
                        verbose_name="AGEM code",
                    ),
                ),
                (
                    "agem_name",
                    models.CharField(
                        help_text="AGEM name of this locality.",
                        max_length=50,
                        verbose_name="AGEM name",
                    ),
                ),
                (
                    "loc_code",
                    models.CharField(
                        help_text="Code of this locality.",
                        max_length=4,
                        verbose_name="locality code",
                    ),
                ),
                (
                    "loc_name",
                    models.CharField(
                        help_text="Name of this locality.",
                        max_length=50,
                        verbose_name="locality name",
                    ),
                ),
                (
                    "history",
                    models.TextField(
                        blank=True,
                        help_text="History of this locality.",
                        verbose_name="history",
                    ),
                ),
                (
                    "interesting_facts",
                    models.TextField(
                        blank=True,
                        help_text="Interesting facts about this locality.",
                        verbose_name="interesting facts",
                    ),
                ),
                (
                    "see_more_at",
                    models.TextField(
                        blank=True,
                        help_text="Links or places where people can find more information about this locality.",
                        verbose_name="see more at",
                    ),
                ),
                (
                    "picture_1",
                    models.ImageField(
                        blank=True,
                        help_text="First picture of this locality that will be shown in its gallery.",
                        upload_to="pictures/localities/",
                        verbose_name="first picture",
                    ),
                ),
                (
                    "picture_1_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the first picture of this locality.",
                        max_length=100,
                        verbose_name="first picture caption",
                    ),
                ),
                (
                    "picture_2",
                    models.ImageField(
                        blank=True,
                        help_text="Second picture of this locality that will be shown in its gallery.",
                        upload_to="pictures/localities/",
                        verbose_name="second picture",
                    ),
                ),
                (
                    "picture_2_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the second picture of this locality.",
                        max_length=100,
                        verbose_name="second picture caption",
                    ),
                ),
                (
                    "picture_3",
                    models.ImageField(
                        blank=True,
                        help_text="Third picture of this locality that will be shown in its gallery.",
                        upload_to="pictures/localities/",
                        verbose_name="third picture",
                    ),
                ),
                (
                    "picture_3_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the third picture of this locality.",
                        max_length=100,
                        verbose_name="third picture caption",
                    ),
                ),
                (
                    "picture_4",
                    models.ImageField(
                        blank=True,
                        help_text="Forth picture of this locality that will be shown in its gallery.",
                        upload_to="pictures/localities/",
                        verbose_name="forth picture",
                    ),
                ),
                (
                    "picture_4_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the forth picture of this locality.",
                        max_length=100,
                        verbose_name="forth picture caption",
                    ),
                ),
                (
                    "picture_5",
                    models.ImageField(
                        blank=True,
                        help_text="Fifth picture of this locality that will be shown in its gallery.",
                        upload_to="pictures/localities/",
                        verbose_name="fifth picture",
                    ),
                ),
                (
                    "picture_5_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the fifth picture of this locality.",
                        max_length=100,
                        verbose_name="fifth picture caption",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug to identify this locality in the website.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata for this record. Change it only if you know what you are doing!",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This timestamp shows when this record was created. This field is populated automatically.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This timestamp shows when this record was last updated. This field is populated automatically.",
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Locality",
                "verbose_name_plural": "Localities",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of this person.",
                        max_length=200,
                        verbose_name="full name",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Alias of this person.",
                        max_length=50,
                        verbose_name="alias",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Date of birth of this person.",
                        null=True,
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "date_of_death",
                    models.DateField(
                        blank=True,
                        help_text="Date of death of this person.",
                        null=True,
                        verbose_name="date of death",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        help_text="Sex of this person.",
                        max_length=1,
                        verbose_name="sex",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        help_text="Biography of this person.",
                        verbose_name="biography",
                    ),
                ),
                (
                    "autobiography",
                    models.TextField(
                        blank=True,
                        help_text="Autobiography of this person.",
                        verbose_name="autobiography",
                    ),
                ),
                (
                    "interesting_facts",
                    models.TextField(
                        blank=True,
                        help_text="Interesting facts about this person.",
                        verbose_name="interesting facts",
                    ),
                ),
                (
                    "anecdotes",
                    models.TextField(
                        blank=True,
                        help_text="Anecdotes of this person.",
                        verbose_name="anecdotes",
                    ),
                ),
                (
                    "see_more_at",
                    models.TextField(
                        blank=True,
                        help_text="Links or places where people can find more information about this person.",
                        verbose_name="see more at",
                    ),
                ),
                (
                    "picture_ft",
                    models.ImageField(
                        blank=True,
                        help_text="Picture of this person that will be shown in the family tree.",
                        upload_to="pictures/people/",
                        verbose_name="family tree picture",
                    ),
                ),
                (
                    "picture_1",
                    models.ImageField(
                        blank=True,
                        help_text="First picture of this person that will be shown in their gallery.",
                        upload_to="pictures/people/",
                        verbose_name="first picture",
                    ),
                ),
                (
                    "picture_1_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the first picture of this person.",
                        max_length=100,
                        verbose_name="first picture caption",
                    ),
                ),
                (
                    "picture_2",
                    models.ImageField(
                        blank=True,
                        help_text="Second picture of this person that will be shown in their gallery.",
                        upload_to="pictures/people/",
                        verbose_name="second picture",
                    ),
                ),
                (
                    "picture_2_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the second picture of this person.",
                        max_length=100,
                        verbose_name="second picture caption",
                    ),
                ),
                (
                    "picture_3",
                    models.ImageField(
                        blank=True,
                        help_text="Third picture of this person that will be shown in their gallery.",
                        upload_to="pictures/people/",
                        verbose_name="third picture",
                    ),
                ),
                (
                    "picture_3_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the third picture of this person.",
                        max_length=100,
                        verbose_name="third picture caption",
                    ),
                ),
                (
                    "picture_4",
                    models.ImageField(
                        blank=True,
                        help_text="Forth picture of this person that will be shown in their gallery.",
                        upload_to="pictures/people/",
                        verbose_name="forth picture",
                    ),
                ),
                (
                    "picture_4_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the forth picture of this person.",
                        max_length=100,
                        verbose_name="forth picture caption",
                    ),
                ),
                (
                    "picture_5",
                    models.ImageField(
                        blank=True,
                        help_text="Fifth picture of this person that will be shown in their gallery.",
                        upload_to="pictures/people/",
                        verbose_name="fifth picture",
                    ),
                ),
                (
                    "picture_5_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the fifth picture of this person.",
                        max_length=100,
                        verbose_name="fifth picture caption",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="If archived, the website will show no information about this person.",
                        verbose_name="is archived?",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug to identify this person in the website.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadata for this record. Change it only if you know what you are doing!",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="This timestamp shows when this record was created. This field is populated automatically.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="This timestamp shows when this record was last updated. This field is populated automatically.",
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
            },
        ),
        migrations.AddConstraint(
            model_name="locality",
            constraint=models.UniqueConstraint(
                fields=("agee_code", "agem_code", "loc_code"), name="unique_locality"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="father",
            field=models.ForeignKey(
                blank=True,
                help_text="Father of this person.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="father+",
                to="civilizations.person",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="locality",
            field=models.ForeignKey(
                blank=True,
                help_text="Locality where this person lived most of their life.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="civilizations.locality",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                help_text="Mother of this person.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mother+",
                to="civilizations.person",
            ),
        ),
    ]
